### ISSUE TITLE
Update 'latest' OCaml version

### ISSUE THREAD

**Issue by dsheets** [ocaml/ocaml-ci-scripts#110]
https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L36 is wrong. See https://github.com/mirage/ocaml-vchan/pull/81#discussion_r63291054.

**Comment by hannesm** [comment]
I don't think having `latest` is a good idea... developers should intentionally choose which major version of OCaml they're testing (having `4.02`, `4.03` etc. pointing to the latest minor is great!)

**Comment by dsheets** [comment]
Removing it is fine with me, too.

**Comment by avsm** [comment]
Agree with removing it -- bumping it is problematic, so we should deprecate it and freeze it at 4.02.3

**Comment by emillon** [comment]
Agree with removing it, this is a bit confusing. Making `latest` builds fail is a bit radical, but I'm worried that a deprecation message will go unnoticed. FTR [a quick search](https://github.com/search?p=1&q=%22OCAML_VERSION+latest%22+filename%3A.travis.yml&ref=searchresults&type=Code&utf8=%E2%9C%93) returns that there are about 70 affected repositories in github.

**Comment by alainfrisch** [comment]
Sorry to piggyback this ticket, but is there currently a simple way to test with OCaml trunk?

**Comment by talex5** [comment]
Could we at least remove `latest` from the documentation then?

https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md#testing-multiple-compilers

**Comment by yomimono** [comment]
The Appveyor tests set a (different, but also old) default version: https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh#L12

**Comment by hannesm** [comment]
closing since #203 is merged (thx @yomimono).  for the `appveyor` tests, please open a fresh issue.
