### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml-ci-scripts#123]
There's quite a lot of unreleased code on `master` (currently 60 commits since the last release, v1.0.2).

It would be useful to have a new release, since some recent changes (e.g. #96) are expected to fix longstanding problems with CI builds such as [this](https://github.com/dsheets/ocaml-unix-fcntl/pull/18#issuecomment-235297623).

**Comment by dsheets** [comment]
How about a release?
