### ISSUE TITLE
Name change causes problems with pinning

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml-ci-scripts#124]
The script [`.travis-docker.sh`](https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh) allows pinning `ocaml-ci-scripts` to enable using features from unreleased versions.

However, the name of the `travis-opam` binary has been [changed](https://github.com/ocaml/ocaml-ci-scripts/commit/4747e2f978093236b74ac48d83d78f397763d511#diff-c0c9029863e47171fc6800ccf1083dd1L2) in recent versions to `ci-opam`.  Since the `ocaml/opam` Docker images and the `.travis-docker.sh` script both still use the old name, pinning recent versions rarely works.

**Comment by yomimono** [comment]
I think everything uses the new name now.
