### ISSUE TITLE
Destination directory of documentation

### ISSUE THREAD

**Issue by mmottl** [ocaml/ocaml-ci-scripts#129]
The docgen script copies the contents of all `*.docdir` directories as follows:

``` sh
cp _build/*.docdir/* $DOCDIR
```

This just clobbered my gh-pages directory.  There are several issues here:
1. If there is more than one `.docdir` directory containing files of the same name (typically `index.html`), the copy command can clobber itself.
2. The user might not even want to have the API-documentation in the topmost directory of the `gh-pages` branch.
3. Documentation files that don't exist anymore will not be removed.

The following may be more closer to what most users want:

``` sh
rsync -a --delete  _build/*.docdir $DOCDIR
```

This would keep API-documentation of distinct libraries of a repository separate and allows the user to have their own `index.html` to refer to the appropriate documentation.

Alternatively, we could introduce new variables to indicate the destination directory or what should happen.  At least for my purposes the above would be perfectly sufficient.

**Comment by dbuenzli** [comment]
> The user might not even want to have the API-documentation in the topmost directory of the gh-pages branch.

FWIW in topkg's `toy-github-delegate`, automatic publication on `gh-pages` is controlled by `opam`'s `doc:` field as described [here](https://github.com/dbuenzli/topkg/blob/5307a83f4ce33c4224d3c75fdac45137e25ccea9/src-bin/toy_github_delegate.ml#L274-L278).

**Comment by mmottl** [comment]
@dbuenzli In my favorite world, all information about packaging and distribution, including location information about documentation, should be specifiable within one file that is part of the distribution.  `opam` files will typically live outside the distribution, because one cannot easily patch old distributions with e.g. new package constraint information.

Oasis may have some rough edges when it comes to supporting complex build processes, but its specification format is a decent starting point.  I believe it may be the better choice for obtaining location information for documentation.

**Comment by dbuenzli** [comment]
> @dbuenzli In my favorite world, all information about packaging and distribution, including location information about documentation, should be specifiable within one file that is part of the distribution.

So what's wrong with using OPAM files for that ? That's actually what `topkg`does (and anyone not using `topkg` can do) and what `odig` expects.

OPAM files have all the metadata fields one needs and there's no need to replicate it in other files or have zillions of different metadata file formats in the eco-system.

FWIW I think we should move towards [this](http://lists.ocaml.org/pipermail/opam-devel/2016-April/001436.html) and is personally the model I assume in what I design nowadays.

> opam files will typically live outside the distribution, because one cannot easily patch old distributions with e.g. new package constraint information.

OPAM files should typically live in your repos (e.g. for `opam pin` or your packager) *and* your distributions (e.g. for system package managers) *and* your package installs (e.g. for `odig`) *and* in OPAM repositories --- each context making different use of the data.

> Oasis may have some rough edges when it comes to supporting complex build processes, but its specification format is a decent starting point.

We should not confuse package build specification and metadata here. `oasis` metadata capabilities have been largely superseeded by `opam` files nowadays, in a package build system independent manner, so generic tools should rely on `opam` files, not `oasis` files.

As a side note I'll just mention that what `oasis` is able to specify is rather limited from a packaging perspective, that is it specifies your build system (and some metadata). `topkg` is much more than this, effectively giving you a, proper, customizable, release process that includes version handling via vcs, distribution linting, reproducible tarball creation, documentation publication, tarball publication and opam submission. This is why I always find a little bit ridiculous when people pit `oasis` against `topkg`, they are not really comparable in their feature set.

**Comment by mmottl** [comment]
I agree with you that OPAM seems like the better format for package metadata.  It is also useful to have within a code repository for e.g. `opam pin`.  But I don't see anything particularly wrong with auto-generating it from another specification either as long as this specification captures most needs.

I also wouldn't mind at all if OPAM usurped more functionality from Oasis, e.g. for specifying builds, and eventually even replaced it.  In the end it boils down to the same thing: how to specify the whole process from building to packaging, distribution, documentation generation, testing, etc., within one well-integrated framework.  It's admittedly asking a lot from one framework, but the productivity gains in software engineering could be substantial and greatly lower the adoption barriers for OCaml.

`topkg` definitely seems like an interesting approach, and maybe I'll try it out for a new project.  Sadly, it's always risky to commit to a new tool that may or may not become standard.  I have changed the way I build and package my software many times in the past.  It's always a significant amount of effort, but not always worth it.

**Comment by dbuenzli** [comment]
> But I don't see anything particularly wrong with auto-generating it from another specification either as long as this specification captures most needs.

Why not but in this case you need the fresh and correct `opam` file in your repo for OPAM `pin`s so that's not really the one you would like to generate.

Aside, this whole auto-generating business should be called for what it is: dodging bureaucratic problems or misdesigned systems by adding layers of indirection. This is why I'm actively seeking for solutions that do not involve auto-generating things. 

> topkg definitely seems like an interesting approach, and maybe I'll try it out for a new project. Sadly, it's always risky to commit to a new tool that may or may not become standard.

Be sure to understand the `t` in the name if you try it, `topkg` is certainly not the final word in this business. However if you deal with many packages and need to release often, the productivity gains can be substantial, see `topkg help release` for the process. If you use `oasis` the migration costs are not that high since you can simply cleanup an ocamlbuild build system generated by `oasis setup` to get started. 

In any case it would be good for your packages to follow the conventions laid out in `odig help packaging` so that your users can easily access your package documentation, changelog and metadata (of course an obvious way of fulfilling these conventions is to switch to `topkg` which implements the convention by default without you having to do anything special).
