### ISSUE TITLE
CircleCI support

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml-ci-scripts#130]
It'd be useful for `ocaml-ci-scripts` to support CircleCI.  [Here](https://circleci.com/docs/configuration/)'s the documentation for the configuration.

**Comment by yomimono** [comment]
@yallop @jhleee is this something you're still interested in?

/cc @djs55 who I think may also be using Circle to test OCaml code?

**Comment by yallop** [comment]
No, I no longer need this.
