### ISSUE TITLE
TravisCI Log Folding

### ISSUE THREAD

**Issue by IgnoredAmbience** [ocaml/ocaml-ci-scripts#131]
Travis' default shell provides the command travis_fold(action, name), where action is either open or close. Its implementation is [here](https://github.com/travis-ci/travis-build/blob/ef82e82457f82c6518d090544bb533dc0faf0063/lib/travis/build/templates/header.sh#L193) and simply involves outputting a string to trigger the fold.

Would it be possible to add these commands/string output into the scripts to make the logs easier to follow?

**Comment by yomimono** [comment]
I didn't know this was possible, but I'd really like it too.

**Comment by samoht** [comment]
That's pretty cool! The only (minor) difficulty is that we want the scripts to work on different environment that TravisCI too (we use the same scripts on CircleCI, Appveyor, etc.). A folding patch respecting this contraint would be gladly accepted!

**Comment by edgemaster** [comment]
Ah, it appears that .travis-docker.sh already has this functionality. (I'm considering moving to using it as 4.03 test jobs are reasonably slow without a PPA backing the compiler installation)...

**Comment by Chris00** [comment]
Anything left to do here (is CircleCI supported at all at the moment)?

**Comment by samoht** [comment]
We use the scripts with CircleCI to test various docker products, so yes it's pretty well supported. I have not checked the result of the fold there, but I guess it just adds some noise to the output...

**Comment by Chris00** [comment]
On 2017-02-14, Thomas Gazagnaire wrote:
>
> We use the scripts with CircleCI to test various docker products, so 
> yes it's pretty well supported.

Cool.  Maybe some instructions should be added to the README?

**Comment by yomimono** [comment]
If a Circle CI user wants to contribute some instructions, I'd happily merge them, but for now I'm going to close this issue.
