### ISSUE TITLE
Update version on brew (system is now 4.04) 

### ISSUE THREAD

**Issue by rleonid** [ocaml/ocaml-ci-scripts#142]
Is there a reason that that the [.travis-ocaml.sh](https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L113) script hasn't been updated to the new 4.04 system switch?

In the current state asking for `4.03.` will switch to system which is now `4.04`.  I'm just wondering if there is a reason besides the "no one has noticed it yet."

**Comment by yomimono** [comment]
This was fixed in #159.  Thanks for reporting it!
