### ISSUE TITLE
Build on MacOSX consistantly fails while Linux passes

### ISSUE THREAD

**Issue by jnavila** [ocaml/ocaml-ci-scripts#147]
See: https://travis-ci.org/jnavila/plotkicadsch/jobs/185877988

The compilation consistantly passes with Linux, but fails as consistantly on Mac ;-)

The compilation fails with the following error:

```
- + /Users/travis/.opam/4.04.0/bin/ocamlfind ocamlopt -a -o src/plotkicadsch.cmxa
- ar: no archive members specified
- usage:  ar -d [-TLsv] archive file ...
- 	ar -m [-TLsv] archive file ...
- 	ar -m [-abiTLsv] position archive file ...
- 	ar -p [-TLsv] archive [file ...]
- 	ar -q [-cTLsv] archive file ...
- 	ar -r [-cuTLsv] archive file ...
- 	ar -r [-abciuTLsv] position archive file ...
- 	ar -t [-TLsv] archive [file ...]
- 	ar -x [-ouTLsv] archive [file ...]
- File "_none_", line 1:
- Error: Error while creating the library src/plotkicadsch.a
- Command exited with code 2.
- E: Failure("Command ''/Users/travis/.opam/4.04.0/bin/ocamlbuild' src/plotkicadsch.cma src/plotkicadsch.native src/plotgitsch.native -tag debug' terminated with error code 10")

```

Digging into similar issues, it seems that the ar utility on MacOSX doesn't accept creating empty archives where as GCC's ar is happy with it.

**Comment by avsm** [comment]
thanks for reporting this -- however, it should go upstream to the https://github.com/ocsigen/tyxml/issues repository rather than this one (which is the central CI script repository)
