### ISSUE TITLE
CI for multi opam packages

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-ci-scripts#166]
Is there a way to test all packages defined in a single git repository? I'm transitioning cohttp away from depopts, and I'd like to make sure travis is still working.

**Comment by avsm** [comment]
This would be very useful.  @Altgr do you think it's worth opening an opam2 enhancement to do multi-pins with one command?  e.g. `opam pin add foo . --all` will pin add the *.opam packages found, rather than just the base package?

**Comment by AltGr** [comment]
I think it's worth it; and it's been there for a while ;)
Just use `opam pin add .` — without the name, and assuming each package properly defines its name (e.g. with file name such as `foo.opam`)

**Comment by samoht** [comment]
It's also possible to do it with opam 1.2 with a bit of gymnastic, see https://github.com/mirage/irmin/blob/master/.travis.yml#L9

**Comment by avsm** [comment]
@altgr thanks, that's really useful!
