### ISSUE TITLE
appveyor fails because of missing jq

### ISSUE THREAD

**Issue by ygrek** [ocaml/ocaml-ci-scripts#167]
Witness https://ci.appveyor.com/project/ygrek/ocurl/build/1.0.6
Any way to fix it on appveyor side?

**Comment by fdopen** [comment]
It's probably already [fixed upstream](https://github.com/ocaml/ocaml-ci-scripts/pull/161). Update https://github.com/ygrek/ocurl/blob/master/appveyor.yml  with https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor.yml

**Comment by ygrek** [comment]
Indeed. Thanks a lot!
