### ISSUE TITLE
Debian Docker images are currently broken

### ISSUE THREAD

**Issue by djs55** [ocaml/ocaml-ci-scripts#171]
This manifests as a failure to download a .deb which looks superficially like a network glitch but is in fact a permanent error.

From https://github.com/mirage/mirage/pull/837 -- we use `unstable` `stable` and `testing` as names but these are aliases and they've recently been bumped, causing the Docker images to be out of sync.

I think we should

- regenerate the Docker images
- perhaps switch to using the release names (`stretch` etc)

**Comment by avsm** [comment]
Ive updated some of the ocaml/opam base images

https://github.com/avsm/ocaml-dockerfile/commit/3ffb108769647f18a1510415a00fa97a8eb7f40b
