### ISSUE TITLE
CI no longer works: master/yorick.mli has moved

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml-ci-scripts#184]
https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-mirage.sh tries to fetch <https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/yorick.mli>. This file no longer exists.

@samoht : looks like you moved this in https://github.com/ocaml/ocaml-ci-scripts/pull/180

**Comment by samoht** [comment]
hum damn. We have no tests for the mirage script, so it's pretty hard to check that they don't break :-( I'll fix that asap

**Comment by talex5** [comment]
Still failing, e.g.

https://travis-ci.org/talex5/qubes-mirage-firewall/builds/276016412

```
2017-09-26 12:55:39 (62.2 MB/s) - ‘travis_mirage.ml’ saved [3830/3830]
+exit 1
The command "bash -ex .travis-mirage.sh" exited with 1.
```

**Comment by samoht** [comment]
should be fixed now

**Comment by talex5** [comment]
Yep - it works now! Thanks.
