### ISSUE TITLE
DEPOPTS broken?

### ISSUE THREAD

**Issue by hannesm** [ocaml/ocaml-ci-scripts#187]
while I can find some `export DEPOPTS=mirage-xen` in [here](https://api.travis-ci.org/jobs/281899645/log.txt?deansi=true), `mirage-xen` itself is never installed!?!?

**Comment by hannesm** [comment]
this may be related to `mirage-xen` also being pinned.

**Comment by hannesm** [comment]
or maybe rather since `TESTS=false`!?

**Comment by yomimono** [comment]
It looks like this is now fixed: https://api.travis-ci.org/v3/job/326443640/log.txt ?
