### ISSUE TITLE
travis-docker defaults to an old travis-opam version

### ISSUE THREAD

**Issue by emillon** [ocaml/ocaml-ci-scripts#193]
When using travis-docker, this part determines what version of travis-opam should be used:

https://github.com/ocaml/ocaml-ci-scripts/blob/0749cbb394f2686011ba0f29b68f4c03da67f2d8/.travis-docker.sh#L36-L42

In particular, this means that by default, the latest version on opam is used. At this time, it means 1.0.3, even though 1.1.0 is released and includes useful fixes such as #146.

I believe that releasing 1.1.0 on opam would be enough to fix this issue.

As a workaround, it is possible to set `FORK_BRANCH=v1.1.0` in the environment.

Thanks!

**Comment by yomimono** [comment]
Thanks for pointing this out, @emillion ! I made [a PR to opam-repository for version 1.1.0](https://github.com/ocaml/opam-repository/pull/11272).

**Comment by yomimono** [comment]
`travis-opam` now gets an upgrade to version 1.1.0 before any action on packages is taken, so I'll close this.  Please feel free to reopen if you see any regression or other unexpected behavior!
