### ISSUE TITLE
Docker-based Travis builds failing with OCaml 4.04

### ISSUE THREAD

**Issue by gaborigloi** [ocaml/ocaml-ci-scripts#199]
Recently most of our Travis builds started failing with the following error:
```
opam: "execvp" failed on ci-opam: No such file or directory
```
For example, this one: https://travis-ci.org/xapi-project/ocaml-netlink/jobs/313427741#L581

The cause is probably this issue: https://caml.inria.fr/mantis/view.php?id=7640

I'd be grateful for any help you can provide :slightly_smiling_face:  - It would be really helpful for us if this was fixed or there was a workaround that we could use to make our Travis builds work again.

**Comment by mseri** [comment]
The issue was due to a too old `ocamlbuild` and or the lack of `travis-opam` in the base repo
