### ISSUE TITLE
What is the license for this code?

### ISSUE THREAD

**Issue by talex5** [ocaml/ocaml-ci-scripts#201]
We're suggesting that people copy these build scripts into their own projects. It would be good to say what the license for these files is.

**Comment by yomimono** [comment]
There are license headers in the OCaml source files ([e.g.](https://github.com/ocaml/ocaml-ci-scripts/blob/master/src/ci_opam.ml)), but those aren't what people are copying around.  I think having a top-level LICENSE.md or similar would be helpful.

**Comment by yomimono** [comment]
Thanks for the PR for this, @samoht :)
