### ISSUE TITLE
jq is not available on some plateforms

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml/ocaml-ci-scripts#208]
Using ```.travis-docker.sh``` on some platforms fails because ```jq``` is not available there.
I could list at least Ubuntu 12.04, CentOS 6 & 7.
Here is the error message on Ubuntu 12.04:
```
The following command needs to be run through "sudo":
    apt-get install -qq -yy jq
E: Unable to locate package jq
OS package installation failed
The command '/bin/sh -c opam depext -ui travis-opam' returned a non-zero code:
```
Source: https://travis-ci.org/mirage/ocaml-github/builds/334114817
Could we find an other way to have those platforms working ? I don't really know where ```jq``` is used here (yet) but maybe we can replace it by something-else or include it in the source code ?

**Comment by yomimono** [comment]
`jq` is used to extract some dependency information (as far as I can tell) from the results of `opam install ---show-actions --json solution.json ${package_list}`, where `package_list` is the package being tested, its depopts, and any extra_deps declared.  The comment explaining why (at a high level) is at https://github.com/ocaml/ocaml-ci-scripts/blob/master/src/ci_opam.ml#L108 , although I admit that I still don't fully understand what's going on there, or whether that level of complexity is needed.  (I'm almost certain that it isn't in opam2, but there are many bits of gymnastics in `ci_opam.ml` that I think opam2 doesn't require.)

**Comment by edwintorok** [comment]
See last comment on https://github.com/ocaml/ocaml-ci-scripts/issues/144, parsing the json output is only needed for opam 1.x. `jq` could be replaced with some OCaml code using a vendored `Jsonm`for example, this script https://github.com/ocaml/ocaml-ci-scripts/blob/a4639edc09ec4a4e72b1b789509cb6e98ba106b0/.travis-mirage.sh will have to be updated when that is done though.

**Comment by yomimono** [comment]
Using a vendored `jsonm` seems like the right solution to me; `jsonm.ml` is compact and permissively licensed.

**Comment by yomimono** [comment]
(I won't have time to do this this week, but if someone else puts together a PR I'll make time to review it)

**Comment by jpdeplaix** [comment]
I'll give it a try today.

**Comment by yomimono** [comment]
Awesome, thanks @jpdeplaix !
