### ISSUE TITLE
appveyor tests set a default ocaml version, and it's pretty old

### ISSUE THREAD

**Issue by yomimono** [ocaml/ocaml-ci-scripts#210]
Documentation claims this will be a "recent" version, which is a fuzzy enough term that I guess 4.03 can qualify: https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh#L12 , but I think we should force users to make this explicit as we've done with Travis.

**Comment by samoht** [comment]
Fixed in #252
