### ISSUE TITLE
Update README-travis.md: pre-4.02 OCaml versions no longer supported

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml-ci-scripts#223]
[README-travis.md](https://github.com/ocaml/ocaml-ci-scripts/blob/c9483edfbd9105f193917595f34e9228f425ac97/README-travis.md#user-content-testing-multiple-compilers) indicates that older OCaml versions are still supported:

> Testing Multiple Compilers
> 
> ```yaml
> env:
>   - OCAML_VERSION=3.12 [...]
>   - OCAML_VERSION=4.00 [...]
>   - OCAML_VERSION=4.01 [...]
>   - OCAML_VERSION=4.02 [...]
> ```

However, #180 removed support for OCaml versions below 4.02, so the suggested configuration does not work.

**Comment by yomimono** [comment]
Thanks for the report!
