### ISSUE TITLE
Cannot build with oasis generated Makefile

### ISSUE THREAD

**Issue by bruce-ricard** [ocaml/ocaml-ci-scripts#226]
Hello,

I initialize my Travis build with the `.travis-ocaml.sh` script, which works fine. Then I try to build my project using my Oasis generated Makefile, but I get this error:
```
+make
ocaml setup.ml -configure 
E: Field 'findlib_version' is not set: Field 'ocamlfind' is not set
```

Looks like other people have had this error in different contexts, but I was enable to find a solution. I made sure that `ocamlfind` was installed. Any idea what this is about? Am I missing a dependency?

**Comment by samoht** [comment]
You probably need this: https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-opam.sh#L20

**Comment by bruce-ricard** [comment]
Thank you @samoht, it worked.

I didn't set `OPAM_INIT` in my `.travis.yml`, so I would guess that it defaults to `true` [here](https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L32) and thus the opam env gets evaluated [there](https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L164). Feels like it should work, but it doesn't.
