### ISSUE TITLE
REVDEPS='*' fails

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocaml-ci-scripts#247]
When enabling `REVDEPS='*'`, the build of packages [fails](https://travis-ci.org/Chris00/ocaml-cairo/jobs/425404448#L1339) with:
```
# mkdir: cannot create directory ‘/home/travis/.opam/4.02.3/lib/ocamlviz’: Read-only file system
```

**Comment by samoht** [comment]
This is not an issue with the CI scripts, right? It just means that ocamlviz.1.01 does not install with opam2 sandbox and should be fixed upstream. Please re-open if I understand the issue wrongly.
