### ISSUE TITLE
Compiler selection '4.02.3' is ambiguous.

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocaml-ci-scripts#259]
When testing for `OCAML_VERSION=4.02`, I got the [failure message](https://travis-ci.org/Chris00/ocaml-odepack/jobs/447368227#L756):
```
[ERROR] Compiler selection '4.02.3' is ambiguous. matching packages: {
        ocaml-base-compiler.4.02.3, ocaml-system.4.02.3 }
The command "bash -ex .travis-opam.sh" exited with 2.
```

**Comment by samoht** [comment]
Thanks, should be fixed by #260

**Comment by Chris00** [comment]
In [view of the error](https://travis-ci.org/Chris00/ocaml-odepack/jobs/447368227#L742), I think you also have to modify [.travis-ocaml.sh](https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L265).

**Comment by samoht** [comment]
See #262
