### ISSUE TITLE
Cygwin: OS package installation failed

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocaml-ci-scripts#283]
The following Appeveyor log: https://ci.appveyor.com/project/kennknowles/ocaml-freetds/branch/master#L352 says first *OS package update successful* and then ends with *OS package installation failed*.  If I [comment out the Cygwin depext](https://github.com/Chris00/ocaml-freetds/commit/e62a5e0b3a6e9b0855d3dd384e38f313a63d7001#diff-154c5bbfbaceb3d29b8510b05f7bf268R39), then it works — but, of course, I do not want to do that.  Despite the fact that it says that depext will not be attempted on this platform, it seems it tries to do something!

**Comment by fdopen** [comment]
The link doesn't work: "Log is empty."
The correct syntax is ```["freetds"] {os = "win32" & os-distribution = "cygwinports"}```. depext-cygwinports should choose the right package (`mingw64-x86_64-freetds` or `mingw64-i686-freetds`) depending on your current compiler.  (`arch` is a global property of your system, but you can use a 32-bit compiler on 64-bit Windows...)

**Comment by Chris00** [comment]
The relevant part is
```
+ opam depext -u freetds
# Detecting depexts using vars: arch=x86_64, os=win32, os-distribution=cygwinports, os-family=windows
# The following system packages are needed:
mingw64-x86_64-freetds
Skipping system update on this platform.
# OS package update successful
Starting cygwin install, version 2.895
User has backup/restore rights
Current Directory: C:\cygwin64\packages
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: C:\cygwin64 system
Selected local directory: C:\cygwin64\packages
net: Preconfig
site: http://cygwin.mirror.constant.com/
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst.sig
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst
solving: 0 tasks, update: no, use test packages: no
Augmented Transaction List: is empty
Changing gid back to original
running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"
running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_desktop-file-utils.sh"
running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_glib2.0.sh"
running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_man-db.sh"
running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_shared-mime-info.sh"
Changing gid to Administrators
Ending cygwin install
installation failed
OS package installation failed
```

**Comment by Chris00** [comment]
> The correct syntax is `["freetds"] {os = "win32" & os-distribution = "cygwinports"}`

Thanks, that works.
