### ISSUE TITLE
Support for Travis + Windows

### ISSUE THREAD

**Issue by ejgallego** [ocaml/ocaml-ci-scripts#284]
Dear OPAM CI devs,

is support for Travis + Windows available / planned?

https://docs.travis-ci.com/user/reference/windows/

I'd be great as this would spare many projects from having to setup more than one CI provider.

**Comment by avsm** [comment]
The Travis Windows support seems fairly slow in my testing. I'd recommend you use https://discuss.ocaml.org/t/github-actions-for-ocaml-opam-now-available/4745/2 instead. Closing this out as it's very unlikely we'll add this unless something changes dramatically in the Travis service.

**Comment by ejgallego** [comment]
Thanks @avsm ; will try out.
