### ISSUE TITLE
'.travis-opam.sh' seems unable to handle name.opam files instead of 'opam'

### ISSUE THREAD

**Issue by hbr** [ocaml/ocaml-ci-scripts#293]
I have renamed at the root of my project the file 'opam' into 'name.opam' in order to adapt to opam 2.0 and dune. Furthermore I want to store multiple opam projects in the same repository.

This was the only change I made in my last commit and the travis ci build failed and before it succeeded.

I have copy and pasted the '.travis.yaml' file into the root of my project and modified nothing.

Any hint on how this issue can be resolved?

Thanks
Helmut

**Comment by Leonidas-from-XIV** [comment]
You could set the `PACKAGE` variable to whatever opam packages you want to install, that works fine. You can see an example of doing that with a single package [in orewa](https://github.com/Leonidas-from-XIV/orewa/blob/2833c0a6e9e16531d6a581484a9c2dbdf6dc092f/.travis.yml#L10) and for multiple packages [in ocaml-zmq](https://github.com/issuu/ocaml-zmq/blob/d312a8458d6b688f75470248f11875fbbfa5bb1a/.travis.yml#L10-L21).

**Comment by hannesm** [comment]
Thanks for your report, as @Leonidas-from-XIV suggested, using `PACKAGE=my-package-name` should do the trick. An example is [tcpip](https://github.com/mirage/mirage-tcpip/blob/master/.travis.yml)'s `.travis.yml`. If this still does not work for you, please report a link to your `.travis.yml`.
