### ISSUE TITLE
Cannot test new .opam packages, it fails to install

### ISSUE THREAD

**Issue by gildor478** [ocaml/ocaml-ci-scripts#314]
Hi,

I am trying to transition ounit OPAM package to ounit2. To do that, I have bot ounit.opam and ounit2.opam and they depend on each other (precise version).

The problem is that it fails to install, because "ounit2" package cannot be found:
```
opam depext -u ounit
+opam depext -u ounit
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
[ERROR] No solution for ounit: The following dependencies couldn't be met:
          - ounit → ounit2 >= 2.1.2
              no matching version
```
The [full logs](https://travis-ci.org/gildor478/ounit/jobs/589294999)

I have already added PINS="ounit2:. ounit:.".

I know that once the package will be published, there will be no more problem -- but I would like to test before sending it to OPAM repository.

Any ways to solve the problem with ocaml-ci-scripts?

**Comment by samoht** [comment]
You can either add a `version` field to your opam files or use `PINS="ounit2.dev:. ounit.dev:."` to pin the package with a specific version (and `dev > [0-9]+`)

**Comment by gildor478** [comment]
Yes, I realized that and I have done that in:
https://github.com/gildor478/ounit/commit/8f33b3e95089b932bbce083a96e5c6795a1a4cb8

Is it worth adding this explanation to the README-travis.md?

Feel free to close the issue.

**Comment by samoht** [comment]
Yes a patch to the README would be very welcome!
