### ISSUE TITLE
Support OCaml 4.11.0 and 4.10.1 in Travis CI

### ISSUE THREAD

**Issue by michael-schwarz** [ocaml/ocaml-ci-scripts#340]
OCaml 4.11.0 and 4.10.1 were recently released, would be good to have them available via the Travis scripts as well without having to set `$OCAML_BETA`:

My guess would be that all that is needed is to add them here

https://github.com/ocaml/ocaml-ci-scripts/blob/fb5b340d1baf11d36820d625d6d6f7de906d3141/.travis-ocaml.sh#L183-L190

and here?

https://github.com/ocaml/ocaml-ci-scripts/blob/fb5b340d1baf11d36820d625d6d6f7de906d3141/.travis-ocaml.sh#L157-L164

**Comment by kit-ty-kate** [comment]
hi, sorry the delay, I forgot to update the scripts. This PR should fix this issue: https://github.com/ocaml/ocaml-ci-scripts/pull/341

**Comment by kit-ty-kate** [comment]
Should be fixed now. Thanks for making this issue
