### ISSUE TITLE
Add a 4.11 switch to docker images

### ISSUE THREAD

**Issue by NathanReb** [ocaml/ocaml-ci-scripts#344]
There's currently no 4.11 switch pre-installed in the docker images so to get a 4.11 build in CI we have to create it from scratch which is a bit slow.

It'd be nice to be able to build on 4.11 without going through all this, especially since 4.12 is almost there!

**Comment by kit-ty-kate** [comment]
cc @avsm who's in charge of the `ocaml/opam2` images

**Comment by NathanReb** [comment]
Ouh yeah my bad, I never remember where exactly I should report those issues. Thanks!

**Comment by kit-ty-kate** [comment]
fixed in https://github.com/ocaml/ocaml-ci-scripts/pull/347
