### ISSUE TITLE
Yorick uses sh but some pre-Elizabethan scripts used bash features

### ISSUE THREAD

**Issue by dsheets** [ocaml/ocaml-ci-scripts#47]
Should we use `bash` or try to stay inside the `sh` feature set? @mor1's port is broken by using `bash`'s string substituion feature `#` for `XENIMG`.

**Comment by mor1** [comment]
Whoops, sorry-- only tested on my site which set this explicitly...

**Comment by yomimono** [comment]
I think this is a non-issue as the offending code is no longer here.
