### ISSUE TITLE
How to avoid an optional dependency being built?

### ISSUE THREAD

**Issue by smondet** [ocaml/ocaml-ci-scripts#70]
I've tried many variations on:

```
    - PACKAGE=biokepi INSTALL=false TESTS=false PINS="trakeva:https://github.com/smondet/trakeva.git ketrew:https://github.com/hammerlab/ketrew.git" DEPOPTS=postgresql EXTRA_DEPS=postgresql PRE_INSTALL_HOOK='opam install postgresql'
```

but the build always fails on MacOSX: https://travis-ci.org/hammerlab/biokepi/builds/82633540
(because of Sqlite needing a hack: https://github.com/smondet/trakeva#sqlite3-on-macosx)

Sqlite3 is an optional dependency and postgresql should replace it →
https://github.com/hammerlab/ketrew/blob/master/opam#L30
how do I convince the ocaml-travisci-skeleton to not install it?

**Comment by yomimono** [comment]
`DEPOPTS` appears to be working as expected these days -- as far as I can tell, the problem you describe isn't replicated in the [ocaml-conduit tests](https://travis-ci.org/mirage/ocaml-conduit/jobs/325817264), which install a subset of their depopts per-test.  I see `biokepi` is using its own testing setup these days, so I won't hassle you about whether you can reproduce this.  Thanks for the report :)
